import { subflow, Message, Custom } from '@robomotion/sdk';

subflow.create('Send PDF Via Outlook', (f) => {
  f.node('b10001', 'Core.Flow.Begin', 'Begin', {})
    .then('b10002', 'Core.Programming.Function', 'Build Attachment List', {
      func: `msg.attachments = [msg.pdf_path];
return msg;`,
    })
    .then('b10003', 'Robomotion.MicrosoftOutlook.SendMail', 'Send Mail', {
      to: Message('recipient_email'),
      subject: Custom('Autogenerated PDF file'),
      body: Custom('Hi,\n\nPlease find the PDF file attached.\n\n-Robomotion for desktop.'),
      attachment: Message('attachments'),
      isBodyHtml: false,
      replyAllMode: false,
    })
    .then('b10004', 'Core.Flow.End', 'End', { sfPort: 0 });
});
