import { flow, Custom, Message } from '@robomotion/sdk';

flow.create('d7e5525b-1ba6-4166-8301-f24f28e0ab7a', 'Imported Translator', (f) => {
  f.node('6082f2', 'Core.Flow.Comment', 'Comment', { optText: '# Translator How-To\n\nThis template uses *Browser*, *File System* and *Dialog* nodes to translate text from one language to another using Google Translate. The text can be provided directly in the configuration or read from a text file. The translation result can be displayed in a dialog box or saved to a text file.\n\n## Usage Steps\n\n### 1. Edit the Config Node\n\nClick on the Config Node to open the settings panel.\n\n### 2. Set Source Language\n\nSet the `msg.translate_from` field to `auto` for automatic language detection, or use the ISO 639-1 code for the specific language you want to translate from. For example: `en` for English, `es` for Spanish, `tr` for Turkish.\n\n### 3. Set Target Language\n\nSet the `msg.translate_to` field to the ISO 639-1 code for the language you want to translate to. For example: `fr` for French, `de` for German, `ja` for Japanese.\n\n### 4. Provide Text Directly (Optional)\n\nSet the `msg.text` field to the text you want to translate if you prefer to input text directly rather than reading from a file. This step is required if you skip step 5.\n\n### 5. Import from Text File (Optional)\n\nSet the `msg.import_from` field to the full filepath of the text file you want to translate. For example: `/Users/username/Documents/text.txt` or `C:\\Users\\username\\Documents\\text.txt`. This step is required if you skip step 4.\n\n### 6. Export to Text File (Optional)\n\nSet the `msg.export_to` field to the full filepath where you want to save the translated text. For example: `/Users/username/Documents/translated.txt`. If not specified, the translation will be displayed in a dialog box.\n\n## Result\n\nWhen the flow is executed, the template will translate your text using Google Translate and either display the result in a dialog box or save it to your specified file location.' });
  f.node('c60a08', 'Core.Trigger.Inject', 'Inject', {})
    .then('a19461', 'Core.Programming.Function', 'Config', { func: 'msg.translate_from = \'en\'; // [Required] (ISO 639-1 code or auto)\nmsg.translate_to = \'tr\'; // [Required] (ISO 639-1 code)\nmsg.text = \'\'; // [Optional] (Required if msg.import_from is empty)\nmsg.import_from = \'/Users/.../message.txt\'; // [Optional] (Required if msg.text is empty)\nmsg.export_to = \'/Users/.../translated.txt\'; // [Optional]\n\n// DO NOT edit below!\nmsg.url = msg.text.length > 0 ?\n  `https://translate.google.com/?sl=${msg.translate_from}&tl=${msg.translate_to}&text=${msg.text}&op=translate` :\n  ``;\n  \nreturn msg;' })
    .then('593d0e', 'Core.Flow.SubFlow', 'Import Text File', {})
    .then('2271d4', 'Core.Browser.Open', 'Open Browser', { optBrowser: 'headlesschrome' })
    .then('d68f24', 'Core.Browser.OpenLink', 'Open Link', { inUrl: Message('url') })
    .then('0ab590', 'Core.Browser.WaitElement', 'Wait Element', { inSelector: Custom('/html/body/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div[1]/div[2]/div[2]/c-wiz/div/div[6]/div/div[1]/span[1]/span/span') })
    .then('f7aa2f', 'Core.Browser.GetValue', 'Get Value', { inSelector: Custom('/html/body/c-wiz/div/div[2]/c-wiz/div[2]/c-wiz/div[1]/div[2]/div[2]/c-wiz/div/div[6]/div/div[1]/span[1]/span/span'), outValue: Message('translation') })
    .then('c9ccac', 'Core.Browser.Close', 'Close Browser', {})
    .then('810392', 'Core.Flow.SubFlow', 'Export Translation', {})
    .then('b95819', 'Core.Flow.Stop', 'Stop', {});
}).start();